export const CLINIC_MODULE_KEYS = [
  "dashboard",
  "patients",
  "appointments",
  "queue",
  "encounters",
  "waitlist",
  "analytics",
  "consents",
  "labs",
  "inventory",
  "tasks",
  "documents",
  "billing",
  "payments",
  "communications",
  "campaigns",
  "automation",
  "reports",
  "catalogs",
  "availability",
  "locations",
  "audit",
  "settings",
  "plan",
  "help",
] as const;