import {
  CalendarClock,
  FileCheck2,
  FlaskConical,
  FolderOpen,
  HandCoins,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  ListOrdered,
  ListTodo,
  LogIn,
  Megaphone,
  MessageCircle,
  Package,
  Repeat,
  ScrollText,
  Search,
  User,
  Wallet,
} from "lucide-react";
import type { FeatureTipDefinition } from "./types";

/**
 * Central registry for all feature tips. Pages only reference `tipId`;
 * the text (via `titleKey`/`descKey`), icon, preferred placement, order,
 * and route allowlist are all declared here so the whole system stays in
 * one place.
 */
const TIP_DEFINITIONS: Array<Omit<FeatureTipDefinition, "tipId"> & { tipId: string }> = [
  {
    tipId: "shell-search",
    titleKey: "tip_shell_search_title",
    descKey: "tip_shell_search_desc",
    icon: Search,
    placement: "bottom",
    order: 0,
    paths: ["/dashboard"],
  },
  {
    tipId: "patients-manage",
    titleKey: "tip_patients_manage_title",
    descKey: "tip_patients_manage_desc",
    icon: User,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "appointments-views",
    titleKey: "tip_appts_views_title",
    descKey: "tip_appts_views_desc",
    icon: LayoutGrid,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "appointments-walkin",
    titleKey: "tip_appts_walkin_title",
    descKey: "tip_appts_walkin_desc",
    icon: LogIn,
    placement: "bottom",
    order: 2,
  },
  {
    tipId: "appointments-recurring",
    titleKey: "tip_appts_recurring_title",
    descKey: "tip_appts_recurring_desc",
    icon: Repeat,
    placement: "top",
    order: 3,
  },
  {
    tipId: "waitlist-status",
    titleKey: "tip_waitlist_status_title",
    descKey: "tip_waitlist_status_desc",
    icon: ListChecks,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "queue-token",
    titleKey: "tip_queue_token_title",
    descKey: "tip_queue_token_desc",
    icon: ListOrdered,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "encounters-charting",
    titleKey: "tip_encounters_charting_title",
    descKey: "tip_encounters_charting_desc",
    icon: FileCheck2,
    placement: "top",
    order: 1,
  },
  {
    tipId: "billing-summary",
    titleKey: "tip_billing_summary_title",
    descKey: "tip_billing_summary_desc",
    icon: Wallet,
    placement: "top",
    order: 1,
  },
  {
    tipId: "payments-status",
    titleKey: "tip_payments_status_title",
    descKey: "tip_payments_status_desc",
    icon: HandCoins,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "labs-ordervsresult",
    titleKey: "tip_labs_ordervsresult_title",
    descKey: "tip_labs_ordervsresult_desc",
    icon: FlaskConical,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "inventory-reorder",
    titleKey: "tip_inventory_reorder_title",
    descKey: "tip_inventory_reorder_desc",
    icon: Package,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "tasks-followup",
    titleKey: "tip_tasks_followup_title",
    descKey: "tip_tasks_followup_desc",
    icon: ListTodo,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "documents-types",
    titleKey: "tip_documents_types_title",
    descKey: "tip_documents_types_desc",
    icon: FolderOpen,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "communications-async",
    titleKey: "tip_communications_async_title",
    descKey: "tip_communications_async_desc",
    icon: MessageCircle,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "campaigns-audience",
    titleKey: "tip_campaigns_audience_title",
    descKey: "tip_campaigns_audience_desc",
    icon: Megaphone,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "consents-log",
    titleKey: "tip_consents_log_title",
    descKey: "tip_consents_log_desc",
    icon: ScrollText,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "audit-append",
    titleKey: "tip_audit_append_title",
    descKey: "tip_audit_append_desc",
    icon: ScrollText,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "availability-template",
    titleKey: "tip_availability_template_title",
    descKey: "tip_availability_template_desc",
    icon: CalendarClock,
    placement: "bottom",
    order: 1,
  },
  {
    tipId: "help-reset-tips",
    titleKey: "tip_help_reset_title",
    descKey: "tip_help_reset_desc",
    icon: Lightbulb,
    placement: "right",
    order: 1,
    paths: ["/help"],
  },
];

const DEFINITIONS_BY_ID = new Map(TIP_DEFINITIONS.map((tip) => [tip.tipId, tip]));

export function getTipDefinition(tipId: string): FeatureTipDefinition | null {
  return DEFINITIONS_BY_ID.get(tipId) ?? null;
}